### ISSUE TITLE
Strip ... from series title

### ISSUE THREAD

**Issue by rossinior** [plexinc-agents/OFDB.bundle#5]
Hey Sander,

brilliant move to open up the OFDB.plugin to TV series. Thx.

A quick fix:

There are also titles of series that have "[TV-Mini-Serie]" or "[Webserie]" added at the end of the title name.
Please also strip these...

I also saw that short movies have "[Kurzfilm]" being added to the title... that could be stripped also.

**Comment by OttoKerner** [comment]
I agree about stripping "[TV-Mini-Serie]" or "[Webserie]", because this is redundant when importing them into a Plex tv show library.

However, there might actually be some people who like the "warning" in the title that this is a "[Kurzfilm]" (short movie).
While I don't like it either, it shouldn't be stripped automatically. 
If there were a user preference about it...

**Comment by sander1** [comment]
Updated in https://github.com/plexinc-agents/OFDB.bundle/commit/2be2a1cf5029a25b82e845cee538995d0db64d9b. It strips away everything at end of the title that is between brackets and at least contains `film` or `serie`.

**Comment by rossinior** [comment]
@OttoKerner isn't der "Kurzfilm" also transported as Genre... so there you have your "warning". The title is the title... ;)

**Comment by OttoKerner** [comment]
I am not sure, because I explicitly disabled the Genre from OFDB. 
They just annoyed me because I rarely agreed with them. ;-)
